// Package neterrors provides adapters for errors generated by the standard net
// package.
//
// Importing this package installs the net errors adapters on the global set of
// adapters of the parent errors-go package.
package neterrors
