// Package pkgerrors provides adapters for errors generated by the
// github.com/pkg/errors package.
//
// Importing this package installs the github.com/pkg/errors adapter on the
// global set of adapters of the parent errors-go package.
package pkgerrors
