// Package ioerrors provides adapters for errors generated by the standard io
// package.
//
// Importing this package installs the io errors adapters on the global set of
// adapters of the parent errors=go package.
package ioerrors
